FROM jupyter/scipy-notebook

RUN pip install --upgrade pip && \
    pip install --upgrade pandas && \
    pip install --upgrade sklearn && \
    pip install --upgrade scikit-image && \
    pip install --upgrade jupyter && \
    pip install jupyterlab
