FROM node:9-onbuild

RUN npm install polymer-cli
RUN npm install bower 
RUN node node_modules/bower/bin/bower install --allow-root

EXPOSE 80

CMD node node_modules/polymer-cli/bin/polymer.js serve -p 80 -H 0.0.0.0
